language: perl
sudo: false

install:
  - perlbrew list
  - cpanm App::af
  - af missing -p configure | cpanm
  - af missing              | cpanm
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

script:
  - dzil test -v

env:
  - ALIEN_INSTALL_TYPE=share
  - ALIEN_INSTALL_TYPE=system
